PATH_TO_SOUND_EVENT_FILES: 'dcase_datagen/metadata/fsd50k/sound_event_filenames.txt'
PATH_TO_SOUND_EVENT_DURS: 'dcase_datagen/metadata/fsd50k/sound_event_durations.txt'
PATH_TO_DATASET: '/home/iran/datasets/FSD50K'
FOLD_NAMES: ['train', 'test']
FOLD_ROOMS: {
  'train': ['tc352','sc203','bomb_shelter','pc226','pb132','se203'],
  'test': ['tb103','sa203','gym'],
}
N_MIX_PER_FOLD: [90, 30]
SNR_RANGE: [6, 31]
MAX_POLYPHONY: 2
MIXTURE_DUR: 60
CLASS_DICT: {
  'femaleSpeech':     0,
  'maleSpeech':       1,
  'clapping':         2,
  'telephone':        3,
  'laughter':         4,
  'domesticSounds':   5,
  'footsteps':        6,
  'doorCupboard':     7,
  'music':            8,
  'musicInstrument':  9,
  'waterTap':         10,
  'bell':             11,
  'knock':            12,
}
SPEED_SET: [10, 20, 40]
NUM_EVENTS_IN_MIXTURE: 5
METADATA_SR: 10
