PATH_TO_SOUND_EVENT_FILES: 'dcase_datagen/metadata/fsd50k/sound_event_filenames.txt'
FOLD_NAMES: ['train', 'test']
FOLD_ROOMS: {
  'train': ['tc352','sc203','bomb_shelter','pc226','pb132','se203'],
  'test': ['tb103','sa203','gym'],
}
